events {}

http {
  server {
    listen 80;
    server_name blog.techvision.local;

    root /var/www/blog;
    index index.html;

    location / {
      try_files $uri $uri/ =404;
    }
  }

  server {
    listen 80;
    server_name docs.techvision.local;

    root /var/www/docs;
    index index.html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
